// <auto-generated />
using BlockerLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Utils.Others.Blocker;

namespace BlockerLib.Migrations
{
    [DbContext(typeof(BlocksDBContext))]
    [Migration("20200108164206_userBlocks-firstMig")]
    partial class userBlocksfirstMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsoleApp4.BlockModel", b =>
                {
                    b.Property<string>("UserKey")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsBlocked");

                    b.Property<int>("NumberOFRetry");

                    b.HasKey("UserKey");

                    b.ToTable("UserBlocks");
                });
#pragma warning restore 612, 618
        }
    }
}
